language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t aman-sehgal-aera/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true aman-sehgal-aera/docker-react npm run test